# Generated by Django 2.0.1 on 2018-01-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=64)),
                ('gender', models.IntegerField(max_length=1)),
                ('telphone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=32)),
                ('name', models.BigIntegerField()),
            ],
        ),
    ]
